### ISSUE TITLE
userid plan

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#107]
/cc @dethe @andreadelrio 

I've been looking into ways of managing user IDs across auth0 and our databases.  I've got a proposal, but want to run it by you before implementing.

Problem: managing userids that don't conflict over two different databases is a pain, especially given that we're not using a SQL db today (and I don't really feel like managing one).  Hard to do atomically in particular.

Facts:
* DynamoDB doesn't have a good way of auto-incrementing IDs (and counting # of items in a dynamodb table is slow or inaccurate depending on the method. See http://stackoverflow.com/questions/12499822/how-can-i-get-the-total-number-of-items-in-a-dynamodb-table 
* Auth0 user_id's are stable over the lifetime of a user, and handle linked accounts and user preferences file
* We have some user data for old data which is not in Auth0, but which would be nice to have, as existing users will want the credit of having authored old cases etc. (desired, not required).

Idea:
* We create auth0 users from the old user database, setting random passwords for these users (they'll have to do a password reset or social login + link accounts to get in).
* As part of the data import, we change from the existing `uid` we have in the old database to a new userid format which is Auth0 compatible, e.g. `old|123` instead of `123`.
* We use Auth0 [rules](https://manage.auth0.com/#/rules/create) to have the login process tell the API server about new users as they show up. Specifically, making it so that everytime a user auths we do a `POST` to `/users/update` and store the relevant bits of the user profile in `pp_users`, thereby having a 'derived' database that we can use at will.
* We use the Auth0 `user_id` field as the key in the `pp_users` table.  Old users will have IDs that look like `old|123`, new users will have IDs that look like `google|123` or `auth0|580bc` depending on whether they used social or username/pw to login first.

The `pp_users` table is where we'd store things that users effectively want to share with other users (e.g. bookmarked entries) or in general which need to be queried in response to actions by users other than the logged in user. 

In this way, we never need to create new userids or worry about userid clashes.

Let me know what you think about this approach.

**Comment by dethe** [comment]
I've never been a fan of creating IDs by autoincrementing integers, especially in any potentially distributed system. That's the problem UUIDs were created to solve, they do it well, and they are widely implemented.

If we give users Auth0 ids of `old|123`, will they keep those ids when they log in with, say, google? If they log in with Google and then with Twitter, do they keep the same ID (seems unlikely, and impossible if they are using a different browser) or get two? This is important because people forget how they logged in (this already bit me) and log in again with a different method.

Given your approach outlined above, the pp_users table then can be completely regenerated from data in Auth0, correct? We'll need to document well that we never update that table ourselves, but only via Auth0 so they don't get out of sync. Is the pp_users table because Auth0 data is slow|opaque|costs per query|other? In other words, since we don't get joins in DynamoDB, what is the value of duplicating data from one DB to another?

<aside>I used to really hate SQL databases, but after working a lot with MongoDB I have really come to appreciate the relational model, and joins in particular. PostgreSQL in particular can be used as a key/value store (it has types for XML and JSON) but can also be used as a relational DB once your schemas settle down, and it has nice types for geographic data, which may be relevant for us.</aside>

I don't have any objections to doing it the way you propose, just want to be sure we're keeping it as simple as we can, because accidental complexity will bite us in the ass later.

**Comment by davidascher** [comment]
My understanding is that if they login with a social account provider which has email associated, they will keep using the `old|123` user_id, except with attached metadata.  It's the 'auto linking' of accounts which deals w/ that issue of not knowing which account is used (as long as they're using the same email, of course).

Well, `pp_users` may or may not be a strict derivative of the user data.  It depends where we choose to keep things like bookmarks.  I could argue either way.

Agreed, I'm trying to keep it simple as well.  I'm definitely not keen on doing social oauth code myself, or dealing w/ password storage, which is why I like using auth0.  I also don't trust SQL databases to do a good job of full-text indexing, but I could be wrong about that.  All of which to say, if you want to move from Dynamo and ES to Postgres, we can consider it, but it seems like a big lift right now.

**Comment by davidascher** [comment]
BTW -- yes, we could create UUIDs.  The main advantage of autoincrementing IDs was that I figured we could use them as slugs until such time as we let users create usernames.  Which isn't super trivial if we still use social logins.

We could just require username/password/email and forego social login but that really will restrict the site to more 'committed' users which seems like an antipattern.

**Comment by dethe** [comment]
I have no idea of the state of full-text indexing in PostgreSQL, but we can keep that in ElasticSearch as easily with a relational DB as with a key/value store, or am I missing something?

**Comment by davidascher** [comment]
Sure, but swapping out Dynamo for SQL doesn't feel like it's actually reducing complexity if we still have lambda triggers and ES.  (but we're drifting off topic of this bug I think)

**Comment by dethe** [comment]
I think my aside about RDBMS is sidetracking us. I'm not seriously proposing we switch to that horse right now, but that not having joins makes it less clear where the right place is for user data.

**Comment by dethe** [comment]
Social code authorization can be a pain, and Auth0 has a nice UI for it. Aside from the UI, the Node library [passport](http://passportjs.org/) makes logins as painless as I've ever experienced, including social media logins. It does require some initial config though, and duplicating the Auth0 UI would probably be a lot of work, so not worth it.

On the other hand, if we're keeping some user data in Auth0 and some in pp_users, that seems like a bad idea to me. It ties us pretty tightly to using Auth0 and we have to remember what gets stored where and/or keep them synchronized. Using Auth0 user_ids to index into pp_users seems fine, and we can keep pp_users the one source of truth for user data.

**Comment by davidascher** [comment]
So I think what'd be easy is to have a table which is a direct derivative copy of the data in auth0, to look up things that are profileish (name, avatar, affiliation), and have a table indexed by user_id which is the bookmarks data. 

Feels like it deals w/ the use cases we have today while splitting auth0-managed data from non-auth0-managed data.

what say you?

**Comment by dethe** [comment]
That sounds like a reasonable compromise.

**Comment by davidascher** [comment]
Done.
