### ISSUE TITLE
Design question: how do we want to show videos and images?

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#202]
In the detail view, should videos be presented in the gallery among the images? First? last?  Some other way?

**Comment by samjiangweb** [comment]
This would depend on context for the video. If categorically... there are multiple, lower priority videos that complement the content - these could go in the gallery. 

If these videos are more crucial to the content - or need to be placed between paragraphs for the right context, then we'll need to insert the embed in the body. 

Typically, we should have video content first - since this is the norm on many news / blog outlets. Here's a handy jQurey plugin to make embedded youtube videos responsive: http://fitvidsjs.com/

**Comment by davidascher** [comment]
For this version, I don't want to add the requirement of managing embedded videos.  There's just a lot of scope creep there.  Our editor component is a 'text' editor, and building the UI for authoring a full rich content thing is just huge.

In practice the stories will just be textual, and the images and videos are complementary to the words.

I think that means we add videos in the gallery.  The authoring UI will be different because we're not uploading videos, just asking for links, but we can render the videos as images in the gallery.

(Aside: we don't use jquery on this site so far, but we'll find a React equivalent).

**Comment by samjiangweb** [comment]
cool beans! yeah videos in gallery it is. and *tear* to no jquery. ;(

**Comment by davidascher** [comment]
I think this is good enough for now.  We can file follow up bugs as needed.
