### ISSUE TITLE
Map view toggle

### ISSUE THREAD

**Issue by samjiangweb** [participedia/frontend#228]
@davidascher would it be possible to toggle different functions for the map? 

Currently we have it so that clicking on countries works as a filter for the results area. 

Maybe some way of toggling the map to do what the current site is doing - zooming in to show individual cases/methods/organizations on the map - perhaps these map markers can be filtered by the case/news/method buttons as well? 

I've attached a really sketchy mockup to show what I mean. (not intended to be finalized design)
![screen shot 2017-04-12 at 6 39 14 pm](https://cloud.githubusercontent.com/assets/25598431/24986491/5b749880-1faf-11e7-958c-7e9c8a1238b5.png)

**Comment by davidascher** [comment]
We can do whatever we want =).  

I'm not a  big fan of the modal approach though, I suspect it'll be confusing.  My guess is it may make sense to just get rid of the "choropleth" country-level coloring and just display pins, that is what people seem to want in informal feedback.  We can keep teh coloring countries map in a special interest section where we show "cool visualizations" maybe?

A couple of things to figure out:

 - do we show all pinsthat exist in the database, or just the pins that match the search, or just the matches that are being displayed below?  My guess is the second, except that we probably want to limit the density of pins or the total number of pins being displayed to avoid crowding.  People can zoom in an area to get more precision.  Sounds right?

 - what happens if people zoom into the map -- does that narrow the search results (see yelp.com's map interactions -- useful, but a bit messy)?  That may be hard to do.

**Comment by samjiangweb** [comment]
Yeah, you're right - I also feel like option two is the way to go. Zooming in should split pin results into more - I get this might be a bit of a challenge if we would like it to make changes to the grid and list as well right?

**Comment by samjiangweb** [comment]
yes. precisely what you mentioned in your second point. hum.

**Comment by davidascher** [comment]
Here's what I suggest as a next step:

a) we dump the color coding and instead display pins for things we have locations for (orgs and cases)
b) we play around with density to see what feels useful
c) we defer updating the list on zoom for now.  In practice people can click on a pin and get to the detail page, so it's not that hard.
d) we explore showing a "country selector" UI somewhere, which does what the current country clicking mode.

**Comment by samjiangweb** [comment]
okay - I have a chat with Amber and Jesi later to get their approval on this - As part of our last discussion we were chatting about what to do with the map.

**Comment by davidascher** [comment]
Did you get a chance to make a decision on this @samjiangweb ?

**Comment by jesicarson** [comment]
@davidascher as per discussions in today's meeting with Amber, your suggestions above (a-c) are approved. we are ok dropping d entirely, but if you want to play with it, feel free. 

@samjianga will readdress the design of the "click to wake map" interaction. Amber suggested some kind of overlay over the entire map.

**Comment by davidascher** [comment]
I think we also agreed that (d) will be a selector widget in the left column somehow.

**Comment by jesicarson** [comment]
Oh right, with the rest of the "popular search" facets that could also possibly work with visualizations? You mentioned a few.. Does that need another issue on github or how does this kind of workflow go? Thanks!

**Comment by davidascher** [comment]
Already created that issue: https://github.com/participedia/frontend/issues/243

**Comment by davidascher** [comment]
I think this is covered in various other bugs.

FYI: the map self-regulates density by avoiding overlapping icons.  As you zoom in, it shows more. I think it's quite effective.
