### ISSUE TITLE
MAP: Decide on what markers to use for cases and orgs in the map

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#260]
We can use any of the icons in material icons (https://material.io/icons/) or font-awesome (http://fontawesome.io/, not sure what version).  I'd prefer it if we didn't have to use new icons, at least for now (because mapbox doesn't make it trivial).

Can pick whatever color, size.

(for implementation, see `MapVisualization.js` and https://github.com/mapbox/mapbox-gl-js/issues/3605#issuecomment-296486123 for the magic incantations.

Currently: 

<img width="439" alt="screenshot 2017-04-23 13 41 15" src="https://cloud.githubusercontent.com/assets/51278/25317278/8b93aa32-282a-11e7-9ece-37acff3b432d.png">

**Comment by samjiangweb** [comment]
@jesicarson @davidascher - If we're limited in terms of icons, then let's go for the standard "place" icon from google material. I'm not certain about colour - I think we should check with amber for approval - My assumption is that black (#333) is preferred (can we add a white outline? + drop/text shadow?) - if not, then we should stick with the interactive colour (red #ec1414). - we should also add a hover state colour - lightened by 15%.

**Comment by davidascher** [comment]
don't we want to distinguish cases & orgs?

**Comment by samjiangweb** [comment]
Well, Stefan had a legend to show different colours and how they correlate
with the markers on the map, I'm cool with that.. though I think it's best
we bring this back to Amber. Based on her feedback, I'd like to hear what
she thinks about introducing more colours into the palette.

With that being said, it wouldn't be a deal breaker if they were all the
same colour, since filtering for cases / organizations - should also filter
the map, right?

**Comment by davidascher** [comment]
It should but it doesn't yet. Good point to notice.

**Comment by jesicarson** [comment]
Two colours might also be fine without a legend, since the word case/org will appear on click in the white box and people will very quickly figure that out. Also it indicates that something multi-layered is going on on the map at first glance. But I agree we should check with Amber. For now I'd say try red and black as Sam suggested. Although for hover, I'm not sure I like the idea of lightening the red, is there another way to indicate hover for red pins, or do we have to? Can it just be click to activate the info box, no hover state change?

**Comment by davidascher** [comment]
Decision is:

- [ ] we'll use black (or dark grey) markers for cases and methods
- [ ] we'll use the highlight color (or a derivative) to show pins that correspond to the search results.

**Comment by jesicarson** [comment]
Black please

**Comment by davidascher** [comment]
took out the remaining bits in #288, closing this.
