### ISSUE TITLE
FEEDBACK WIDGET - Align left & match red colour

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#274]
Is it possible to match the red of the button on the footer to the red we use in the site? If not, then black or grey would be better. 

Also align to the left edge of the hamburger menu.

**Comment by davidascher** [comment]
Not possible to fine tune colors.

<img width="313" alt="screenshot 2017-04-25 09 54 04" src="https://cloud.githubusercontent.com/assets/51278/25397525/63bf0d48-299d-11e7-8561-e02aa1ea90b3.png">


I picked red because I think black/grey is actually too easy to miss. At least during the user testing phase, I want people to notice this thing and be curious -- I think we can decide once we launch whether to keep it or tone it down, but I was worried people would just never notice it otherwise.

**Comment by jesicarson** [comment]
Bummer. Do you think grey is too subtle? What about yellow? Maybe even magenta would work.. I'd say green but its a bit Christmas. Do they have that bright rgb internet blue? The red is just too close and too wrong, needs to change to something. More contrast is fine. 

Can we fix the alignment also?

**Comment by davidascher** [comment]
Alignment choices are similarly coarse:

<img width="639" alt="screenshot 2017-04-25 10 28 33" src="https://cloud.githubusercontent.com/assets/51278/25398773/00992ff0-29a2-11e7-83b8-4f337930a5ae.png">

I'll pick a grey, you can react.

**Comment by jesicarson** [comment]
Alrighty then :)

**Comment by jesicarson** [comment]
I think grey is better.
