### ISSUE TITLE
DESIGN: what dates do we want to show in the search results?

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#291]
The current implementation is a bit weird:

<img width="294" alt="screenshot 2017-04-26 22 05 04" src="https://cloud.githubusercontent.com/assets/51278/25468695/762778a0-2acc-11e7-9050-420412f571e6.png">

One of those dates is the date the thing was created, the other is the date of the last modification.  One is expressed in formal date language, the other in human "x months ago" type language.

I think we lost some fidelity in this process along the way.  We should figure out:

- which date matters
- whether we need to show authorship and/or last-editor.

In the spirit of wikipedia, and a less cluttered search results page, my suggestion is:

- we don't show names of authors or editors  in the search results page
- we only show one date, probably the 'last edited' date, and using human language.

Opinions?  @jesicarson as the proxy for the community in particular.

**Comment by jesicarson** [comment]
Sure! I agree with Davids suggestions. And... there are some additional notes about search results on latest redpen (https://redpen.io/ar95785df6be9283e4):
- Move the content type label (CASE) below the image, above case title.
- Bookmark: This move will allow for space for the bookmark icon below the bottom right corner of the image.
- Featured: Rather than a star or any featured icon, add the word FEATURED before the content type label for featured items, ie: FEATURED CASE

**Comment by samjiangweb** [comment]
@davidascher @jesicarson @andreadelrio - Let's also removed the "8 months ago" and replace it with the [last edited date] or [publish date] (Which one do you think Jesi?) - We won't need to indicate time, only the date - I'd recommend this format: "DD Month, YYYY" or "9 May, 2017" because mm/dd/yy can be confusing between date and month.

**Comment by jesicarson** [comment]
What about "May 9, 2017"

**Comment by samjiangweb** [comment]
sure! as long as we have a clear month and date ;)

**Comment by jesicarson** [comment]
Cool lets go with that.

**Comment by andreadelrio** [comment]
Covered in PR #303
