### ISSUE TITLE
Footer links should link to something

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#304]
Footer links currently all seem to go to "#". I know some of this is waiting on having search working better, but I wanted to flag it so we don't forget.

**Comment by jesicarson** [comment]
News, Help & Contact are the only links that don't work in the footer as of today. 

- [ ] Create an issue & mockup for help page (jesi)

- [ ] Create an issue & mockup for contact page (jesi)

- [ ] Create an issue & mockup for news page (jesi)

@dethe do you think we should remove "News" from footer for now, until it is built (since it's removed from the homepage)? What do you think about keeping Help and Contact in the footer, even though they don't work? Thx.
