### ISSUE TITLE
Default text not needed for Quick Submit

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#520]
Via @jesicarson, she doesn't feel like we need all that text in the body of a new Case/Method/Organization. I know we put it there to suggest some structure for things that we don't capture as metadata elsewhere. I'm not sure what the right way is, but ultimately this is a design / requirements issue, so if she wants it gone we can remove it.

**Comment by jesicarson** [comment]
@dethe - We do indeed need the headings for the full submit body narratives. But in quick submit ideally we only want a short description (esp on mobile when all these suggested headings get really long and messy to scroll down without clicking in the text box). 

My suggested solution would be to bring back the "summary" field for quick submit, and only include the long narrative in the full submit (which would be a separate field, with all the headings). Make sense? But instead of "summary", I'd call it something like "Short..." or "Tweet-length description of this case/ method/ organization" with a text box that has a limited word count.

**Comment by dethe** [comment]
@jesicarson OK, but either way it becomes the body of the Case/etc., right? Or do we need to add a new field for summary?

1. We can drop the default text in Quick Submit mode and add it if they click full submit (if they haven't added other text yet).
2. We can have a short field but I don't know why we'd actually limit the word count if they want to add more detail.

**Comment by jesicarson** [comment]
@dethe It just hit me that the quick sub form was never updated to match Pat's criteria (issue #399 )   There's also [a mockup](https://drive.google.com/open?id=0B5j_dGoSFCLJVFE2OXloN0ZCNFE) to that effect. So per that, we aren't supposed to have a description in quick submit at all. Now, this could be up for debate, but that was the decision by Pat for this round of testing, so I say lets go with that.

**Comment by dethe** [comment]
Ah, so if we fix those issues we can close this. I will need to make a minor change on the backend, right now it requires both a title and description (or body) at a minimum.

**Comment by dethe** [comment]
@jesicarson We might want to promote that mockup to its own issue, I would not have thought of looking for it under "Clean up typography in quick submit flows".

**Comment by jesicarson** [comment]
Lol, true. It did make sense at the time, as thats where that visual cleanup work was taking place and it needed a mockup - although when Sam couldn't do it I guess it got dropped. Anyway, sure I can make a new issue for it :) 

And yes, fixing those issues would void this one.

**Comment by dethe** [comment]
Will be covered by #522, so closing this issue. Thanks, @jesicarson!
