### ISSUE TITLE
Editing a case/ method/ org should only show quick sub fields

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#549]
(@dethe let me know if this was what you had in mind when we discussed this this morning)

When a user clicks on the edit button on any case/method/org, they'll see just quick sub fields. Below that will be two buttons: "Save" & "Edit Full Version"

If "Edit full version" is clicked, the rest of the fields are revealed, with "Save" below that. 

*RELATED QUESTIONS: do the forms auto save? and what is the status of version control?

**Comment by dethe** [comment]
Related:

https://github.com/participedia/usersnaps/issues/75

**Comment by dethe** [comment]
@jesicarson For your related questions: no, forms do not currently auto-save, except where the browser does this for us. Version control is not 100% implemented, but basic version control is maybe 70% done.

**Comment by jesicarson** [comment]
@dethe Thanks! More questions:
Is allowing users to save their entries as drafts something that is very complex? This was proposed early on, but got dropped along the way.
Is there any visual design required for version control from ui perspective? Do you need mockups?

**Comment by dethe** [comment]
Saving entries as drafts shouldn't be complex, unless I am missing something. We already have a `published` flag that we set automatically when they submit, it would just be a matter of *not* setting it, not showing unpublished items by default, and the UI for handling it all.

Some questions (we should probably promote this to its own issue):

1. Can an item be retracted to draft state again once it has been published?
2. Are further edits to a published item automatically published as well?
3. I'm assuming only the author can see draft items, but do we need any further roles/workflow like editors who can see all (even draft) items? Keeping in mind that the more roles and states, the more complicated everything gets.
4. Likewise, I'm assuming only the author can publish a draft item (or retract to draft state, if we allow that), but is that the case?
5. There was something else, but I've forgotten it now.

For versioning, yes, will need mockups, but also rules.

1. If there are five versions and the user reverts to version 3, what happens to versions 4 and 5? Can they be reverted to, or are they discarded and we just move forward from version 3? I'm assuming we'd keep them and be able to revert to them, but for users used to `undo` that may be different from what they expect.
2. How much detail do we need to provide to show what has changed between versions?
3. Can anyone revert a change or only a subset of users?
4. I won't even start on the localization issues just now…
5. Right now we're only prepared to version title and body, not metadata. If versioning all changes is required this becomes a much more complicated issue.

**Comment by jesicarson** [comment]
Great questions @dethe. I think @plscully should weigh in here also (on the original issue, as well as these follow up issues). I'm going to add this to the agenda for next week's call.

**Comment by plscully** [comment]
@jesicarson @dethe .  Re: "Saving entries as drafts" please see my responses below. 

My recollection is that some folks want this feature primarily so that they can work on the narrative/article section w/out having to complete it before posting. They don't want other users to think that a draft reflects their polished work.

The simplest overall solution is probably to remind users that it's best to write their content with their preferred word processor and then paste the final copy into PPedia.  Or perhaps we should borrow from Wikipedia and provide a sandbox where users can develop the narrative section and then copy/paste or export it into a case that also includes the other data fields.

1. Can an item be retracted to draft state again once it has been published?
- Seems like a low priority and overly complex if the originating contributor sees revisions from another user he doesn't like and decides to retract to a draft state.  If a user publishes by mistake they would have to bite the bullet and use our editing tools. If something goes horribly wrong, they could write to us and ask us to delete the case so that they can start over.

2. Are further edits to a published item automatically published as well?
- Yes, I would leave this function as it now is. Again, perhaps some of this would be more manageable if we used the Wikipedia set of options: save changes, show preview, show changes

3. I'm assuming only the author can see draft items, but do we need any further roles/workflow like editors who can see all (even draft) items? Keeping in mind that the more roles and states, the more complicated everything gets.
- Probably good for a small # of admin/editors to see draft items IF we are concerned that we could end up with lots of "ghost" drafts abandoned by users. Admins could then turn them into stubs. But if there is a work-around that can do this just as well, then lets do that.

4. Likewise, I'm assuming only the author can publish a draft item (or retract to draft state, if we allow that), but is that the case?
- Per 3 above, if we allow admin/editors to see and publish abandoned drafts, Scott and I will develop guidelines re: which parts of the draft are published (under an official "anonymous" user account) so that the originating user isn't upset that we published something they never wanted the world to see.

**Comment by plscully** [comment]
@jesicarson @dethe RE: questions about Versioning rules. Please see my bulleted replies below.

1. f there are five versions and the user reverts to version 3, what happens to versions 4 and 5? Can they be reverted to, or are they discarded and we just move forward from version 3? I'm assuming we'd keep them and be able to revert to them, but for users used to undo that may be different from what they expect.
- I agree that "versions 4 & 5" should be kept. As far as I know, we haven't received negative feedback about this aspect of the current site.

2. How much detail do we need to provide to show what has changed between versions?
- I don't know enough about how this usually works to have an informed opinion. However, one of the things we wanted on the current site that I don't think we ever achieved was to also show changes in the data fields. As far as I know, now we can only view changes in the article body.

3. Can anyone revert a change or only a subset of users?
- As it is now, anyone can revert a change. This has worked well, although it seems as though we need someway to identify/track users who make reversions. Perhaps set it so that only someone who has made at least a small edit to the entry can revert a change. 

4. I won't even start on the localization issues just now…

5. Right now we're only prepared to version title and body, not metadata. If versioning all changes is required this becomes a much more complicated issue.
- I don't know enough to understand the implications of this. Does this refer to the issue I addressed in 2 about making it possible to view changes in all the data fields. If so, and if this is a huge problem, we can put it off until a later update.

**Comment by jesicarson** [comment]
@dethe @andreadelrio, 
RE: The original issue 549... After chatting with @plscully today, we decided to default to show only the quick submit fields when a user clicks edit on a case, method or org. 
As per above:
- When a user clicks on the edit button on any case/method/org, they'll see just quick sub fields. Below that will be two buttons: "Save" & "Edit Full Version"
- If "Edit full version" is clicked, the rest of the fields are revealed, with "Save" below that.

**Comment by jesicarson** [comment]
related: #592

**Comment by jesicarson** [comment]
I forgot to mention also that we'd like to create some expert user tricks to default to the full entry form. 
1. in user settings, have a toggle for this
2. create a keyboard shortcut (ie: shift + click edit = full form loads)

**Comment by scottofletcher** [comment]
Hey folks, just going to give my two cents to this: I agree with everything that's been said about versions and drafts - one thing I'd just request is for an admin to be notified when a user reverts an entry to a previous version. I don't see this happening very often but where I do see it happening is when someone closely related to a project/organization etc. has written an entry and doesn't want any additions (eg. 'negative' aspects added to the Analysis section). I'd also suggest building in something to the back end that allows admins to disable edits or version revisions on certain entries - that way we won't get into the 'editing wars' I've watched unfold on Wikipedia.

**Comment by plscully** [comment]
Good idea!



*From:* Scott Fletcher [mailto:notifications@github.com]
*Sent:* Monday, November 6, 2017 3:22 PM
*To:* participedia/frontend <frontend@noreply.github.com>
*Cc:* Patrick Scully <pscully@clearviewconsultingllc.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [participedia/frontend] Editing a case/ method/ org should
only show quick sub fields (#549)



Hey folks, just going to give my two cents to this: I agree with everything
that's been said about versions and drafts - one thing I'd just request is
for an admin to be notified when a user reverts an entry to a previous
version. I don't see this happening very often but where I do see it
happening is when someone closely related to a project/organization etc.
has written an entry and doesn't want any additions (eg. 'negative' aspects
added to the Analysis section). I'd also suggest building in something to
the back end that allows admins to disable edits or version revisions on
certain entries - that way we won't get into the 'editing wars' I've
watched unfold on Wikipedia.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/participedia/frontend/issues/549#issuecomment-342274174>,
or mute the thread

**Comment by jesicarson** [comment]
Thanks @scottofletcher. Ive added your comment above to the [changes from .net doc](https://docs.google.com/document/d/1laEc11Y3PN41IaDuFluIl1UiEsONLifM1NPYEVgI1AI/edit?usp=sharing) under "admin tools", which Dethe and I will be reviewing in the next couple of weeks in order to define admin roles. You could revisit that doc and see if there's anything you want to add. 

Basically we want to end up with a list of tasks that admins are able to do for this issue: https://github.com/participedia/frontend/issues/672
