### ISSUE TITLE
Need mockup for News page

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#598]

**Comment by jesicarson** [comment]
Include tags 
Other metadata?
Not editable by non-admins

@dethe did we decide not to include news on the homepage? i cant find it in the notes. i assume since i added an issue to mockup a news page, it should be it's own page... thoughts? 

I recall we discussed having a separate page for the user community listings, with its own separate search... can we add a syntax thing like "user: name here" so ppl can use the search bar for this, and it auto populates the search bar when someone goes to the user community page? or is that weird? this would apply to

**Comment by dethe** [comment]
Yes, I believe we decided to remove News from the front page for now. Doesn't look like we ever made an issue for that, though.

**Comment by jesicarson** [comment]
@dethe I know we removed it from the homepage search filter menu (where cases, methods and orgs are now), but did we decide it needed it's own separate page and wouldn't ever be put back on the menu? I can't remember, but possibly because full text search might bring up news articles in results and how would that fit into a download of the csv? Which also brings up the question (possibly a silly one): how would a search result that included cases, methods and orgs all together be downloaded in one csv?

**Comment by dethe** [comment]
No, I think the plan was to put it back on the homepage and in all the places once we actually implement News. Good question about the CSV. Right now we actually only support downloading JSON, which can support lists of different types of object. But for CSV support there are basically two ways we can go: Download a separate CSV file for each object type (possibly zipped together), or one CSV file which has all the properties of all the objects, with blanks where any given object doesn't have that property. I think the first one is probably more useful, but for now we don't have to worry because JSON doesn't have the same limitation.

**Comment by jesicarson** [comment]
Ok, in that case we won't need a mockup for a new news page, since news results will look the same as the other content types on the homepage. News reader pages would basically be the same as a case, minus location map and data. So this can be closed I think.
