### ISSUE TITLE
"Related Content" should be a header like "Data" on reader view of content

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#646]
Currently it's displayed under data, in the main data list:
![screen shot 2017-09-27 at 4 21 27 pm](https://user-images.githubusercontent.com/13560530/30942497-68ed237c-a3a0-11e7-8edb-d9d073e580ec.png)

It should be it's own heading, as per [mockup](https://drive.google.com/open?id=0B5j_dGoSFCLJejlCVjQxLWk4Q1E):
![case](https://user-images.githubusercontent.com/13560530/30942537-95f8d7ee-a3a0-11e7-847b-166878e0cb42.jpg)

**Comment by jesicarson** [comment]
@scottofletcher can you clarify/ further explain this comment from user testing: "Do we need a field for 'Related Methods'? This might just clutter things up - I think it's better if we just capture the methods/tools used in this case and then, if a user is interested, they can go to the methods entry which will have links to related methods. In short: cases should have a field for 'Related Cases', methods should have a field for 'Related Methods', organizations should have a field for 'Related Organizations'." 
Maybe we should chat about this in person? I'm not sure if we have the same idea of what related content is supposed to achieve, and this is an important piece to be clear on so we can communicate to users how to properly use this feature.

**Comment by scottofletcher** [comment]
@jesicarson let's set up a skype call on Slack :)

**Comment by scottofletcher** [comment]
Hey @jesicarson, I've been thinking about this issue and I don't think we should include 'Methods' and 'Organizations' under the 'Related Content' heading since those fields are part of the data set and so should, technically, be under 'Data'. In fact, 'Methods' is perhaps one of the most important case data fields for comparative researchers. "Related Content" still sounds like it's referring to orgs/methods that weren't directly involved in this case. Are we still going to have Data sub-headings for "Methods and Tools Used" and "Type of Implementing Entity" or are they being replaced with the sub-headings under 'Related Content'?

**Comment by jesicarson** [comment]
Hi @scottofletcher. The design decision to highlight related content was exactly for that reason - because methods is likely important to people who are interested. We wanted to put it in a header of its own to call attention to it. It doesn't mean that it's not part of the data or the export, that will all be the same. its only called out in the reader view so people can easily see it. Yesterday I drafted some explanatory text for what related content means in this issue https://github.com/participedia/frontend/issues/572. Check it out and let me know what you think. again, perhaps its the word "related" that's not working?

**Comment by dethe** [comment]
We ditched related content altogether, closing this.
