### ISSUE TITLE
Allow users to delete (hide) their own content

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#687]
Right now we limit hiding articles to admins, but users should be able to remove their own content from view as well.

This does raise issues about ownership and transparency:

1. Can only the original author of an article delete it, and do contributing authors get notified?
2. Do we show this option as "Hide content" (true, but confusing) or "Delete content" (fits user expectations, but misleading).

**Comment by scottofletcher** [comment]
Here's how Wikipedia deals with this: https://en.wikipedia.org/wiki/Wikipedia:How_to_delete_a_page
I agree with their method - no one except admins should be able to permanently hide or delete content, even if they are the author. Having some kind of 'tagging' or 'reporting' system is probably the best option.

**Comment by jesicarson** [comment]
We don't allow users to hide/delete content because of all the authorship/contributor issues. 

We can add an FAQ item about requesting deletion. ie: "How do I delete content? Only admins can delete content on Participedia..." etc. (we can borrow some of the language from the wikipedia link that scott posted - good stuff). 

Note that we still need to deal with version control (https://github.com/participedia/frontend/issues/587) before we can fully explain the system to users.

**Comment by jesicarson** [comment]
Added an FAQ item to the copy deck for @andreadelrio to add to the help sidebar.
