### ISSUE TITLE
(surge form review) Edits needed to "Evaluation Links" in case form 

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#747]
Inconsistency between case forms on surge and in Strong Draft 10 

Case forms:
1 - Label: Evaluation Reports
Instructional text: Upload relevant documents here.
Placeholder: Upload relevant documents
2 - Label: Evaluation Links
Instructional text: evaluation_links_instructional_undefined
Placeholder evaluation_links_placeholder_undefined

<img width="443" alt="screenshot 2018-02-20 18 07 09" src="https://user-images.githubusercontent.com/29512491/36459532-f5da3280-1668-11e8-9e01-ab44d5c814fb.png">

Strong Draft 10 
Label: Evaluation Report (appears if “yes” selected in question 4 [Formal Evaluation])
Instructional text: Upload or provide a link to the evaluation report here. 
Field type A: URL
Field type B: upload from device

@plscully @jesicarson can you advise?

**Comment by jesicarson** [comment]
I believe we talked about this with @dethe and decided to make it into 2 questions, one for links, one for documents, because having them both in the same question complicated the data collection. So basically we need to write instructional text and placeholder for evaluation report docs links. 

@plscully does this work:

Label - Upload Evaluation Report
Instructional - Upload the evaluation report from your device.
Placeholder - Upload from device

Label - Provide a link to Evaluation Report
Instructional - Provide a link to the evaluation report here. 
Placeholder - Add a link

**Comment by jesicarson** [comment]
OR labels could be:
Evaluation Report Document
Evaluation Report Link

**Comment by plscully** [comment]
@jesicarson @dethe Yes, this should be divided into two questions. And I prefer the 2nd, shorter labels.
