### ISSUE TITLE
Search BUGS Cannot search from entry view / searches don't clear

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#836]
Search bar does not work on any page except the home page.

**Comment by scottofletcher** [comment]
Lucy just messaged me on Slack telling me this bug is very disruptive to her workflow

**Comment by jesicarson** [comment]
Noted. I just messaged Lucy to see if we can find a work around for now. Thanks for the flag.

**Comment by jesicarson** [comment]
Hi @dethe - I just got clarification from Lucy that its not having to go to the homepage to search that is slowing her down, it's because the map takes so long to load each time. She checked her internet connection and that shouldn't be a problem for her, however, I can't replicate the map loading issue, mine loads quite quickly. I recommended that she try scrolling down the screen (hiding the map) before searching. Hopefully that will make a difference until we can fix this, but not sure. 

At any rate, wondering if you think this bug should be prioritized? I hesitate because there are so many other things on your plate. Thanks!

**Comment by scottofletcher** [comment]
Thanks @jesicarson and @dethe  - I'm actually finding that having to go to the homepage to search is slowing down my work not necessarily because it takes so long to load but just because it takes longer in general. 

I'm also getting a little frustrated not being able to clear a search or return to just cases, orgs, or methods without going to the homepage first. For example, if I search for citizens' assembly, clicking on 'cases', 'orgs', or 'methods' will filter my search. However, if I want to clear my search and just see all the organizations, I have to first go to the home page and then scroll down and select orgs.

**Comment by jesicarson** [comment]
Oh ya that is frustrating. Search doesn't clear when you return to the homepage, you have to re-load the page. @dethe I assume these bugs are all connected?
