### ISSUE TITLE
Same Entry, Different Titles in Profile View

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#865]
_From @davidascher on June 26, 2018 21:47_

**Sender**: scottowenfletcher@gmail.com
**Comment**: Able to Select the Same Method From Different Tiles. Clicking 'CARE Community Score Card' brings you to the same page as clicking 'Community Score Card' does - the former is more up-to-date (changed the title), the latter shouldn't appear at all. Same thing with 'Community Forestry' and 'Community Forestry Groups'
[Open #224 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/224)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-26/23-46/2a086b68-20be-4aa0-8e32-84e17e0168ff.png'>![Usersnap Feedback - Able to Select the Same Method From Different Tiles. Clicking 'CARE Commun(...)](https://usersnappublic.s3.amazonaws.com/2018-06-26/23-46/a4bfd909-84cc-453f-9472-5028cbca43d0.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-26/23-46/2a086b68-20be-4aa0-8e32-84e17e0168ff.png'>Download original image</a>

**Browser**: Firefox 60 (Windows 10)
**Referer**: [https://participedia.xyz/users/417712](https://participedia.xyz/users/417712)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

_Copied from original issue: participedia/usersnaps#211_

**Comment by scottofletcher** [comment]
NOTE: the duplicates don't show up on regular search - only when you're looking through Robert's entries from his profile page

**Comment by ascott** [comment]
@davidascher it looks like the issue here is with the API. 

GET `/users/{id}` returns multiple case objects for the same id. it looks like it includes a case for every time i have edited it.

<img width="556" alt="screenshot 2019-03-08 11 18 42" src="https://user-images.githubusercontent.com/130878/54050543-534c8600-4194-11e9-91ad-b2fe884803d3.png">

i could fix this on the frontend by looking for duplicate ids, and then sorting by updated date and only showing the latest updated case. 

it's probably a better idea to fix this in the API, but I haven't been able to figure out what's going on there yet. my local db is only showing a single entry for this id, so i'm not sure how it is returning multiple. any ideas?
