### ISSUE TITLE
Username & Profile Name Should Be Same

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#873]
_From @davidascher on July 5, 2018 18:5_

**Sender**: jesi.carson@gmail.com
**Comment**: The "name" on my profile should be my username, but it doesn't work to log in. 

Also, our button says "Login" and Autho says "Log In" this should be consistent.
[Open #233 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/233)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-05/20-03/5c1e64cb-0999-4965-8ee1-0866e1a55b6a.png'>![Usersnap Feedback - The "name" on my profile should be my username, but it doesn't work to log (...)](https://usersnappublic.s3.amazonaws.com/2018-07-05/20-03/23951084-0ee9-4ec9-97a4-a0ac8b7746ec.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-05/20-03/5c1e64cb-0999-4965-8ee1-0866e1a55b6a.png'>Download original image</a>

**Browser**: Chrome 67 (Macintosh)
**Referer**: [https://participedia.xyz/](https://participedia.xyz/)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 703

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

_Copied from original issue: participedia/usersnaps#220_

**Comment by dethe** [comment]
Jesi and I have decided we don't need username, users will log in with their email address. So profile name should just be their name.

**Comment by scottofletcher** [comment]
@dethe will this fix all the usernames that currently appear in the 'Submitted by' field? How/will this impact admins changing names on entries?

**Comment by dethe** [comment]
@scottofletcher I'm not sure what "all the usernames that currently appear in the 'Submitted by' field" means. This won't change users or listing them, it will only means we will use their `name` rather than pretend that we have a `username` field in any meaningful way. For uniquely identifying users we have a numeric id and their email, we don't need a unique username. Their name can be whatever they choose to be known by, but preferably their real, full name.

Admins changing names on entries will be given a searchable list of existing users, so this should have little or no impact on that feature.

**Comment by scottofletcher** [comment]
@dethe I meant that, for example, [this case](https://participedia.xyz/case/609) would show that it was 'First submitted by' Robert Richards and not richards1000
